on:
  schedule:
    - cron: '30 15 * * 0' # Runs every Sunday at 15:30

jobs:
  curl-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run scripts/createIndexHtml.sh
      run: |
        chmod +x scripts/createIndexHtml.sh
        ./scripts/createIndexHtml.sh

    - name: Commit and push if it changed
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update HTML file with upcoming events"
        git push