on:
  schedule:
    - cron: '0 13 * * 1,6' # Runs every Monday and Saturday at 13:00

jobs:
  curl-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version you need

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scrapeEventUrls.py
      run: |
        python scrapeEventUrls.py

    - name: Commit and push if it changed
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update HTML file with upcoming events"
        git push